# This is a basic workflow to help you get started with Actions

name: Nightly Branch Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push of toxophilist/sprint-dev branch or periodic
  push:
    branches: 
      - 'toxophilist/sprint-dev'
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: toxophilist/sprint-dev

      # Merge sprint-dev
      - name: Merge toxophilist/sprint-dev
        run: |
          git status
          git fetch
          git pull
          git checkout origin/nightly
          git status
          git merge --allow-unrelated-histories toxophilist/sprint-dev -m Nightly
          git push origin HEAD:nightly
        shell: bash
